import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

const CONTENT = `# CiCode Language Reference for AI Agents

> This file was generated by the CiCode VSCode extension.
> Source: AVEVA Plant SCADA 2023 R2 – CiCode Reference Manual.
> Keep this file up to date by running **Cicode: Add AI Context Files** from the Command Palette.

---

## What is CiCode?

CiCode is the scripting language for AVEVA Plant SCADA (formerly Citect SCADA).
It is a procedural, event-driven language used to automate SCADA operations:
form dialogs, tag reads/writes, SQL queries, page navigation, alarms, trends, and more.

---

## Data Types

| Type      | Size    | Notes                                        |
|-----------|---------|----------------------------------------------|
| INT       | 32-bit  | Signed integer                               |
| REAL      | 64-bit  | Double-precision float                       |
| STRING    | ≤255 B  | Fixed max length — use StrLeft to pad/trim   |
| OBJECT    | 32-bit  | Handle to a Plant SCADA runtime object       |
| QUALITY   | 64-bit  | OPC quality value                            |
| TIMESTAMP | 64-bit  | Timestamp value                              |

---

## Variable Scope

| Scope    | Keyword  | Declared at            | Lifetime                        |
|----------|----------|------------------------|---------------------------------|
| Global   | GLOBAL   | File level             | Entire project, all files       |
| Module   | (none)   | File level (default)   | This file only                  |
| Local    | (none)   | Inside a function body | Duration of that function call  |

- Add \`PERSISTENT\` before the type to survive runtime restart:
  \`PERSISTENT INT nCounter;\`
- **Arrays can NOT be declared inside function bodies** — use module or global scope.

---

## Function Declaration Syntax

\`\`\`cicode
! Return type on the line BEFORE the FUNCTION keyword (omit for void)
INT
FUNCTION MyFunction(INT nParam1, STRING sParam2)
    ! Local variable declarations come FIRST, before any executable statements
    INT    nLocal;
    STRING sResult;

    nLocal = nParam1 + 1;
    sResult = sParam2 + IntToStr(nLocal);
    RETURN nLocal;
END
\`\`\`

Key rules:
- Return type (INT, REAL, STRING, OBJECT) goes on its own line **above** \`FUNCTION\`.
- Void functions omit the return type line entirely.
- All local variable declarations must appear at the **top** of the function body.
- Function names: max 32 characters, case-insensitive at call sites.
- \`RETURN\` exits the function; bare \`RETURN;\` for void functions.

---

## Control Flow

### IF … THEN … ELSE … END

\`\`\`cicode
IF nValue = 10 THEN
    DoSomething();
ELSE
    DoOther();
END
\`\`\`

### FOR … DO … END

\`\`\`cicode
INT i;
FOR i = 0 TO 9 DO
    ProcessItem(i);
END
\`\`\`

### WHILE … DO … END

\`\`\`cicode
WHILE nRow < 500 DO
    IF MyArray[nRow][0] = "" THEN
        nRow = 500;             ! break by setting counter to exit value
    ELSE
        ProcessRow(nRow);
        nRow = nRow + 1;
    END
END
\`\`\`

> Always call \`Sleep(10);\` inside infinite WHILE loops to yield CPU and avoid
> Plant SCADA performance degradation.

### SELECT CASE … END SELECT

\`\`\`cicode
SELECT CASE nStatus
    CASE 1
        Prompt("Waiting");
    CASE 2, 3
        Prompt("Active");
    CASE 4 TO 10
        Prompt("Running");
    CASE IS > 100
        Prompt("Error");
    CASE ELSE
        Prompt("Unknown");
END SELECT
\`\`\`

---

## Operators

| Category   | Operators                          |
|------------|------------------------------------|
| Arithmetic | \`+\`  \`-\`  \`*\`  \`/\`  \`MOD\`        |
| Relational | \`=\`  \`<>\`  \`<\`  \`>\`  \`<=\`  \`>=\` |
| Logical    | \`AND\`  \`OR\`  \`NOT\`               |
| Bitwise    | \`BITAND\`  \`BITOR\`  \`BITXOR\`      |
| Format     | \`Value:FormatStr\` (e.g. \`n:###.##\`) |

**Operator precedence** (highest → lowest):
\`()\` > \`NOT\` > \`* / MOD\` > \`:\` > \`+ -\` > \`> < <= >=\` > \`= <>\` > \`AND\` > \`OR\` > \`BITAND BITOR BITXOR\`

---

## String Escape Sequences

| Escape | Meaning       |
|--------|---------------|
| \`^n\`   | Newline       |
| \`^t\`   | Tab           |
| \`^"\`   | Double quote  |
| \`^^\`   | Caret literal |

---

## Comments

\`\`\`cicode
! Single-line comment
// Single-line comment
/* Multi-line
   comment */
\`\`\`

---

## Arrays

\`\`\`cicode
! Module-level or global-level declaration (NEVER inside a function)
STRING MyData[500][5];      ! 500 rows × 5 columns, zero-indexed
GLOBAL INT nCounts[100];    ! Global 1-D integer array

! Access
sVal = MyData[nRow][nCol];
MyData[0][0] = "Hello";
\`\`\`

---

## Semicolons

Required after every **executable statement**.
**Not** required after block keywords: \`FUNCTION\`, \`END\`, \`IF\`/\`THEN\`/\`ELSE\`,
\`FOR\`/\`DO\`, \`WHILE\`/\`DO\`, \`CASE\`, \`END SELECT\`.

---

## String Functions

| Function    | Signature                                  | Description                              |
|-------------|--------------------------------------------|------------------------------------------|
| StrLeft     | \`StrLeft(sStr, nLen)\`                      | Leftmost N characters                    |
| StrRight    | \`StrRight(sStr, nLen)\`                     | Rightmost N characters                   |
| StrMid      | \`StrMid(sStr, nStart, nLen)\`               | Substring from nStart for nLen chars     |
| StrLength   | \`StrLength(sStr)\`                          | Length of string                         |
| StrTrim     | \`StrTrim(sStr)\`                            | Remove leading and trailing whitespace   |
| StrReplace  | \`StrReplace(sStr, sFind, sReplacement)\`    | Replace all occurrences                  |
| StrUpper    | \`StrUpper(sStr)\`                           | Convert to uppercase                     |
| StrLower    | \`StrLower(sStr)\`                           | Convert to lowercase                     |
| StrSearch   | \`StrSearch(sStr, sPattern)\`                | Find substring position (0-based, -1=not found) |
| StrFill     | \`StrFill(sChar, nCount)\`                   | Build string of repeated character       |
| StrToInt    | \`StrToInt(sStr)\`                           | Parse string to INT                      |
| StrToReal   | \`StrToReal(sStr)\`                          | Parse string to REAL                     |
| IntToStr    | \`IntToStr(nInt)\`                           | INT to string                            |
| RealToStr   | \`RealToStr(rReal, nWidth, nPlaces)\`        | REAL to fixed-width string (**3 args!**) |

> **RealToStr requires 3 arguments**: Number, Width (total field width), Places (decimal places).
> Calling it with 2 args will crash at runtime. Example: \`RealToStr(3.14159, 10, 2)\` → \`"      3.14"\`

---

## Math Functions

\`Abs\`, \`Int\`, \`Round\`, \`Pow\`, \`Sqrt\`, \`Log\`, \`Ln\`, \`Sin\`, \`Cos\`, \`Tan\`, \`Asin\`, \`Acos\`, \`Atan\`

---

## SQL Functions — Standard Pattern

\`\`\`cicode
INT hSQL;
STRING sName;
STRING sValue;

hSQL = SQLConnect("DSN=MyDSN;UID=user;PWD=pass");
IF hSQL = -1 THEN
    ! Connection failed — check SQLErrMsg()
    RETURN;
END

SQLExec(hSQL, "SELECT Name, Value FROM MyTable WHERE ID = " + IntToStr(nID));
WHILE SQLNext(hSQL) = 0 DO
    sName  = SQLGetField(hSQL, "Name");
    sValue = SQLGetField(hSQL, "Value");
    ! process row …
END
SQLEnd(hSQL);
SQLDisconnect(hSQL);
\`\`\`

### Parameterized Queries (recommended — avoids SQL injection)

\`\`\`cicode
INT hSQL;
INT hStmt;

hSQL  = SQLConnect("DSN=MyDSN");
hStmt = SQLQueryCreate(hSQL);
SQLSet(hStmt, "SELECT * FROM Products WHERE Code = @Code");
SQLParamsSetAsString(hStmt, "Code", sCode);
SQLGetRecordset(hStmt, "");
WHILE SQLNext(hStmt) = 0 DO
    sDesc = SQLGetField(hStmt, "Description");
END
SQLQueryDispose(hStmt);
SQLDisconnect(hSQL);
\`\`\`

### SQL Function Reference

| Function             | Description                                         |
|----------------------|-----------------------------------------------------|
| SQLConnect           | Open connection, returns handle (−1 on failure)     |
| SQLDisconnect        | Close connection                                    |
| SQLExec              | Execute a query string                              |
| SQLNext              | Advance to next row (returns 0 while rows exist)    |
| SQLGetField          | Read a field value from current row (returns STRING)|
| SQLEnd               | Release current result set                          |
| SQLNumChange         | Number of rows affected by last INSERT/UPDATE/DELETE|
| SQLRowCount          | Number of rows in current recordset                 |
| SQLErrMsg            | Get last SQL error message                          |
| SQLBeginTran         | Begin transaction                                   |
| SQLCommit            | Commit transaction                                  |
| SQLRollBack          | Roll back transaction                               |
| SQLAppend            | Append string to SQL buffer (for >255 char queries) |
| SQLSet               | Set query string in buffer                          |
| SQLQueryCreate       | Create a query handle for parameterized queries     |
| SQLQueryDispose      | Dispose a query handle                              |
| SQLParamsSetAsString | Bind a STRING parameter                             |
| SQLParamsSetAsInt    | Bind an INT parameter                               |
| SQLParamsSetAsReal   | Bind a REAL parameter                              |
| SQLParamsClearAll    | Clear all bound parameters on a connection          |
| SQLNoFields          | Number of fields in result set                      |
| SQLIsNullField       | Check if a field value is NULL                      |
| SQLFieldInfo         | Get metadata about a result field                   |

> **SQL string escaping**: When building dynamic SQL with string values, always escape single
> quotes: \`StrReplace(sVal, "'", "''")\` — otherwise a value like \`"O'Brien"\` breaks the query.

---

## Form (Dialog) Functions

\`\`\`cicode
FormNew("Dialog Title", nWidth, nHeight, 0);
FormPrompt(nX, nY, "Label text:");
FormEdit(nX, nY, nWidth, sVar, 0);
FormListBox(nX, nY, nWidth, nHeight, sBuf, 1);
FormAddList("Item to add");
FormCheckBox(nX, nY, "Check label", nVar, 0);
FormComboBox(nX, nY, nWidth, sVar, 0);
FormButton(nX, nY, "  OK  ", 0, 1);
FormButton(nX, nY, " Cancel ", 0, 2);
nResult = FormRead(0);     ! 0 = OK pressed; non-zero = other button / closed
FormDestroy();
\`\`\`

> \`FormNew\`, \`FormPrompt\`, \`FormListBox\`, \`FormAddList\`, \`FormButton\`, etc. are **built-in
> Form functions** — they are NOT the \`FOR\` loop keyword despite starting with "For".

---

## Page Navigation

\`\`\`cicode
PageDisplay("PageName");
PageBack();
PageForward();
PageHome();
PagePrev();
PageNext();
\`\`\`

---

## Tag Functions

\`\`\`cicode
TagRead("TagName");                ! Read tag value → STRING
TagWrite("TagName", sValue);       ! Write tag value
TagGetProperty("TagName", "Units");
\`\`\`

---

## Task / Background Execution

\`\`\`cicode
TaskNew("MyFunction", "", 8);      ! Start MyFunction as background task
TaskKill(hTask);
Sleep(nMilliseconds);              ! Yield CPU; always use in WHILE loops
\`\`\`

---

## Macros (Conditional Compilation)

\`\`\`cicode
#IFDEF DEBUG
    Print("debug info");
#ENDIF

#IFNDEF PRODUCTION
    ! non-production only code
#ENDIF
\`\`\`

---

## Known Gotchas for AI Agents

1. **\`<>\` not \`!=\`** — not-equal operator is \`<>\`. Never write \`!=\`.
2. **Keywords must be uppercase** — \`WHILE\`, \`FOR\`, \`IF\`, \`THEN\`, \`ELSE\`, \`END\`,
   \`FUNCTION\`, \`RETURN\`, \`GLOBAL\`, \`INT\`, \`STRING\`, \`REAL\`, \`AND\`, \`OR\`, \`NOT\`, \`DO\`, \`TO\`, \`MOD\`.
3. **\`RealToStr\` requires 3 args** — \`RealToStr(Value, Width, Places)\`. A 2-arg call
   crashes at runtime in Plant SCADA.
4. **No arrays inside function bodies** — arrays must be declared at module or global scope.
5. **Local variables declared first** — all \`INT\`, \`STRING\`, \`REAL\` declarations in a
   function must appear before any executable statement.
6. **STRING max 255 bytes** — truncated silently; use device files or multiple strings for larger data.
7. **\`FOR\` is a loop keyword** — function names like \`FormNew\`, \`FormListBox\`, \`FormulaLoad\`
   are **not** the \`FOR\` keyword; they are valid identifiers/built-ins.
8. **\`Sleep()\` in loops** — always call \`Sleep(10);\` (or similar) inside long WHILE loops
   to avoid CPU starvation and Plant SCADA performance issues.
9. **SQL strings need escaping** — embed single-quote values with \`StrReplace(s, "'", "''")\`.
10. **\`FOR\` loop: no STEP keyword** — CiCode FOR loops always increment by 1. To count
    differently, use a WHILE loop with manual increment.
11. **Module-level executable statements** run at SCADA startup — place initialisation code
    there only if intended.
12. **\`RETURN\` with value** — for INT/REAL/STRING functions, \`RETURN nValue;\`.
    For void functions, \`RETURN;\` or just fall off the end.
`;

// ---------------------------------------------------------------------------
// Command implementation
// ---------------------------------------------------------------------------

export function registerAiContextCommand(
  context: vscode.ExtensionContext,
): vscode.Disposable {
  return vscode.commands.registerCommand(
    "cicode.addAIContext",
    async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) {
        vscode.window.showErrorMessage(
          "Cicode: No workspace folder open. Please open a folder first.",
        );
        return;
      }

      const root = folder.uri.fsPath;

      // --- CLAUDE.md ---
      const claudePath = path.join(root, "CLAUDE.md");
      fs.writeFileSync(claudePath, CONTENT, "utf8");

      // --- .github/copilot-instructions.md ---
      const githubDir = path.join(root, ".github");
      if (!fs.existsSync(githubDir)) {
        fs.mkdirSync(githubDir, { recursive: true });
      }
      const copilotPath = path.join(githubDir, "copilot-instructions.md");
      fs.writeFileSync(copilotPath, CONTENT, "utf8");

      const choice = await vscode.window.showInformationMessage(
        "Cicode: Created CLAUDE.md and .github/copilot-instructions.md",
        "Open CLAUDE.md",
      );
      if (choice === "Open CLAUDE.md") {
        const doc = await vscode.workspace.openTextDocument(claudePath);
        await vscode.window.showTextDocument(doc);
      }
    },
  );
}
